# Generated by Django 3.1.4 on 2020-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20201214_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinchart',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
